<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>여행 숙소 후보</title>

<style>

body{
font-family: Arial;
background:#f4f6f8;
margin:0;
padding:20px;
}

h1{
text-align:center;
margin-bottom:30px;
}

.container{
max-width:900px;
margin:auto;
}

.card{
background:white;
border-radius:14px;
padding:15px;
margin-bottom:25px;
box-shadow:0 5px 12px rgba(0,0,0,0.1);
}

.slider{
display:flex;
overflow-x:auto;
gap:10px;
margin-bottom:15px;
}

.slider img{
width:260px;
height:180px;
object-fit:cover;
border-radius:8px;
flex-shrink:0;
}

.name{
font-size:20px;
font-weight:bold;
margin-bottom:5px;
}

.price{
color:#ff4d4d;
font-weight:bold;
margin-bottom:10px;
}

.desc{
margin-bottom:10px;
line-height:1.5;
}

.buttons a{
display:inline-block;
padding:8px 14px;
margin-right:8px;
background:#4CAF50;
color:white;
text-decoration:none;
border-radius:6px;
font-size:14px;
}

.map{
background:#2196F3 !important;
}

</style>

</head>

<body>

<h1>🏝 제주 여행 숙소</h1>

<div class="container">

<!-- ================= 숙소 1 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/property/64371805/999633387/1479d44bb1cf7d4612c87207e2725b18.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/64371805/999633387/26e7457aa3c49ecf81c74fd323d7465b.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/64371805/999633387/0a0eefaf7dc12f40fa559cd18b6597eb.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/64371805/999633387/3fd89001dd5f7ec0b0ca50e78a3aff30.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/64371805/999633387/567d7aa7a405d86c89cd842196895fde.jpeg?ce=0&s=800x">

</div>

<div class="name">
제주 오션스위트애월
</div>

<div class="price">
가격 (1박 102,276원)
</div>

<div class="desc">

✔ 스위트 갤러리 오션뷰<br>
✔ 특징2<br>
✔ 특징3

</div>

<div class="buttons">

<a href="http://agoda.com/ko-kr/jeju-ocean-suite-aewol/hotel/jeju-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=33ea6ec3-3eb9-41eb-8bab-e253139bfd13&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10" target="_blank">예약보기</a>

<a class="map" href="http://map.naver.com/p/search/%EC%A0%9C%EC%A3%BC%ED%8A%B9%EB%B3%84%EC%9E%90%EC%B9%98%EB%8F%84%20%EC%A0%9C%EC%A3%BC%EC%8B%9C%20%EC%95%A0%EC%9B%94%EC%9D%8D%20%EA%B0%80%EB%AC%B8%EB%8F%99%EA%B8%B8%2077?searchType=address" target="_blank">지도보기</a>

</div>

</div>


<!-- ================= 숙소 2 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/hotelImages/81170501/1273298906/5296554efbe3977aa4ede0bce37e8a7e.jpg?ce=3&s=800x">
<img src="https://pix8.agoda.net/property/81170501/951511572/aa70d32980a6ac9d4928bea2c0542ae2.jpeg?ce=3&s=800x">
<img src="https://pix8.agoda.net/property/81170501/951511572/02e84cded2385372859b3437b77105cb.jpeg?ce=3&s=800x">
<img src="https://pix8.agoda.net/property/81170501/951487048/7edf60b44c296f0e4c9ef4b3c438bd4e.jpeg?ce=3&s=800x">
<img src="https://pix8.agoda.net/hotelImages/81170501/1273298906/6e9912f1c106503522c4ccddc199ca97.jpg?ce=3&s=800x">

</div>

<div class="name">애월 더 선셋 풀빌라 리조트</div>

<div class="price">가격 (1박 151,870)</div>

<div class="desc">

✔ 오션 테라스 스탠다드<br>
✔ 특징<br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/aewol-the-sunset-resort/hotel/seogwipo-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=4961e589-4bf3-4e0f-a53f-7bbfdb8bd954&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10&ds=LzaVtxcYQ9hHA3%2Fs"_blank">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%EC%95%A0%EC%9B%94%20%EB%8D%94%20%EC%84%A0%EC%85%8B%20%ED%92%80%EB%B9%8C%EB%9D%BC%20%EB%A6%AC%EC%A1%B0%ED%8A%B8/place/1751609884?c=15.00,0,0,0,dh&isCorrectAnswer=true&placePath=/home?from=map&fromPanelNum=1&additionalHeight=76&timestamp=202603132352&locale=ko&svcName=map_pcv5&searchText=%EC%95%A0%EC%9B%94%20%EB%8D%94%20%EC%84%A0%EC%85%8B%20%ED%92%80%EB%B9%8C%EB%9D%BC%20%EB%A6%AC%EC%A1%B0%ED%8A%B8&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>


<!-- ================= 숙소 3 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/property/32250741/519291279/da589af1052370df481777f4d02b52a2.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/1196654/-1/92d9dee17074a042e6a866249f256047.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/32250741/792451930/61d42c408fcaf12ec406d6c32eee3b64.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/32250741/792451930/0bba62652d2fd359b3997605b792c41d.jpeg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/32250741/792451930/61d42c408fcaf12ec406d6c32eee3b64.jpeg?ce=0&s=800x">

</div>

<div class="name">샐리스 제주 호텔</div>

<div class="price">가격 (1박 64,481)</div>

<div class="desc">

✔ 스탠다드 오션뷰<br>
✔ 싱글베드 1개 + 퀸베드 1개<br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/sallys-jeju-hotel/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=4961e589-4bf3-4e0f-a53f-7bbfdb8bd954&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%EC%83%90%EB%A6%AC%EC%8A%A4%20%EC%A0%9C%EC%A3%BC%20%ED%98%B8%ED%85%94/place/37917639?c=15.00,0,0,0,dh&placePath=/home?bk_query=%EC%83%90%EB%A6%AC%EC%8A%A4%20%EC%A0%9C%EC%A3%BC%20%ED%98%B8%ED%85%94&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132354&locale=ko&svcName=map_pcv5&searchText=%EC%83%90%EB%A6%AC%EC%8A%A4%20%EC%A0%9C%EC%A3%BC%20%ED%98%B8%ED%85%94&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>

<!-- ================= 숙소 4 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/property/47542244/819686259/0c32320366557ca20ad66382c5c0508b.jpeg?ce=3&s=800x">
<img src="https://pix8.agoda.net/hotelImages/114/1140664/1140664_16090614160046139094.jpg?ca=6&ce=1&s=800x">
<img src="https://pix8.agoda.net/property/32250741/792451930/61d42c408fcaf12ec406d6c32eee3b64.jpeg?ce=0&s=800x">

<img src="https://pix8.agoda.net/hotelImages/114/1140664/1140664_16090614160046139089.jpg?ca=6&ce=1&s=800x">

</div>

<div class="name">탐라 스테이 호텔 제주</div>

<div class="price">가격 (1박 55,685)</div>

<div class="desc">

✔ 스탠다드 오션뷰<br>
✔ 싱글베드 1개 + 퀸베드 1개<br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/sallys-jeju-hotel/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=4961e589-4bf3-4e0f-a53f-7bbfdb8bd954&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="https://map.naver.com/p/search/%ED%83%90%EB%9D%BC%20%EC%8A%A4%ED%85%8C%EC%9D%B4%20%ED%98%B8%ED%85%94%20%EC%A0%9C%EC%A3%BC/place/37116745?c=15.00,0,0,0,dh&placePath=/home?bk_query=%ED%83%90%EB%9D%BC%20%EC%8A%A4%ED%85%8C%EC%9D%B4%20%ED%98%B8%ED%85%94%20%EC%A0%9C%EC%A3%BC&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132355&locale=ko&svcName=map_pcv5&searchText=%ED%83%90%EB%9D%BC%20%EC%8A%A4%ED%85%8C%EC%9D%B4%20%ED%98%B8%ED%85%94%20%EC%A0%9C%EC%A3%BC&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>

<!-- ================= 숙소 5 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/hotelImages/391594/-1/da6d46fe2521c4fef619c4613d86a6fa.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/7eca7ae66ec39d474fa7e383483d94cc.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/e480c532dc8f814759e6e137b54a3917.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/ab1c8918cab78a476c90bc8e8aadab95.jpg?ca=13&ce=1&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/6dfd5c02dbd711d67368e296d8fd1b90.jpg?ca=13&ce=1&s=800x">

</div>

<div class="name">탑스텐 빌라드애월</div>

<div class="price">가격 (1박 102,125)</div>

<div class="desc">

✔ 디럭스 패밀리 트윈룸<br>
✔ 더블베드 1개 + 싱글베드 1개<br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/villa-de-aewol_7/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=4961e589-4bf3-4e0f-a53f-7bbfdb8bd954&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%ED%83%91%EC%8A%A4%ED%85%90%20%EB%B9%8C%EB%9D%BC%EB%93%9C%EC%95%A0%EC%9B%94/place/16870181?c=15.00,0,0,0,dh&placePath=/home?bk_query=%ED%83%91%EC%8A%A4%ED%85%90%20%EB%B9%8C%EB%9D%BC%EB%93%9C%EC%95%A0%EC%9B%94&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132356&locale=ko&svcName=map_pcv5&searchText=%ED%83%91%EC%8A%A4%ED%85%90%20%EB%B9%8C%EB%9D%BC%EB%93%9C%EC%95%A0%EC%9B%94&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>

<!-- ================= 숙소 6 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/hotelImages/391594/-1/da6d46fe2521c4fef619c4613d86a6fa.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/7eca7ae66ec39d474fa7e383483d94cc.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/e480c532dc8f814759e6e137b54a3917.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/ab1c8918cab78a476c90bc8e8aadab95.jpg?ca=13&ce=1&s=800x">
<img src="https://pix8.agoda.net/hotelImages/391594/-1/6dfd5c02dbd711d67368e296d8fd1b90.jpg?ca=13&ce=1&s=800x">

</div>

<div class="name">애월 오션 스테이</div>

<div class="price">가격 (1박 102,125)</div>

<div class="desc">

✔ 테라스 트윈 - 저층, 인피니티풀 무료사용포함<br>
✔ 싱글베드 1개 + 퀸베드 1개<br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/dyne-oceano-hotel_2/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&los=2&searchrequestid=4961e589-4bf3-4e0f-a53f-7bbfdb8bd954&utm_medium=banner&utm_source=naver&utm_campaign=naverbz&utm_content=nbz10&utm_term=nbz10&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%EC%95%A0%EC%9B%94%20%EC%98%A4%EC%85%98%20%EC%8A%A4%ED%85%8C%EC%9D%B4/place/1604784907?c=15.00,0,0,0,dh&placePath=/home?bk_query=%EC%95%A0%EC%9B%94%20%EC%98%A4%EC%85%98%20%EC%8A%A4%ED%85%8C%EC%9D%B4&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132356&locale=ko&svcName=map_pcv5&searchText=%EC%95%A0%EC%9B%94%20%EC%98%A4%EC%85%98%20%EC%8A%A4%ED%85%8C%EC%9D%B4&businessCategory=pension" target="_blank">지도보기</a>

</div>

</div>

<!-- ================= 숙소 7 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/hotelImages/29537497/-1/0bdcae41de4526b2ff8899b3625279a7.jpg?ce=0&s=800x">
<img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/403315544.jpg?k=d68c63d86970b02216e25247a7b1d0dad3184d53324473bf3f4aeb0a40585b88&o=&s=800x">
<img src="https://pix8.agoda.net/hotelImages/29537497/469621436/450c373a1620507e44acec424b209124.jpg?ca=25&ce=0&s=800x">
<img src="https://pix8.agoda.net/property/69691641/0/a81bdfdd2d5278bf5224dfa811612c90.jpeg?ce=2&s=800x">
<img src="https://pix8.agoda.net/hotelImages/29537497/-1/76f022b406f79f890238e60c7586e727.jpg?ca=25&ce=0&s=800x">

</div>

<div class="name">호텔 시리우스</div>

<div class="price">가격 (1박 106,908)</div>

<div class="desc">

✔ 시티뷰 스위트<br>
✔ 킹베드 1개br>
✔ 특징

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/hotel-sirius_3/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&tspTypes=8&los=2&searchrequestid=4aca703a-0619-4516-ba02-5543a3db80b6&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%ED%98%B8%ED%85%94%20%EC%8B%9C%EB%A6%AC%EC%9A%B0%EC%8A%A4/place/1278914403?c=15.00,0,0,0,dh&placePath=/home?bk_query=%ED%98%B8%ED%85%94%20%EC%8B%9C%EB%A6%AC%EC%9A%B0%EC%8A%A4&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132356&locale=ko&svcName=map_pcv5&searchText=%ED%98%B8%ED%85%94%20%EC%8B%9C%EB%A6%AC%EC%9A%B0%EC%8A%A4&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>

<!-- ================= 숙소 8 ================= -->

<div class="card">

<div class="slider">

<img src="https://pix8.agoda.net/hotelImages/748442/75954836/d211921e9ffbe7bb59997182b46fc2c0.jpg?ce=0&s=800x">
<img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/134703724.jpg?k=c951c37c2006bf221502f5a64649a9c5d1873f965d83fc1a1969e9cf4838b32b&o=&s=800x">
<img src="https://pix8.agoda.net/hotelImages/748442/75954836/ce06cf1e8b360b0b3e215a79197c5938.jpg?ce=0&s=800x">
<img src="https://pix8.agoda.net/property/748442/0/d56195c76efa4fb9393722178dedf0fa.jpeg?s=800x">
<img src="https://pix8.agoda.net/hotelImages/748442/-1/fc3802d3ab9d66f9ffc380264be3e0d0.jpg?ca=0&ce=1&s=800x">

</div>

<div class="name">그라벨 호텔</div>

<div class="price">가격 (1박 92,524)</div>

<div class="desc">

✔ 디럭스 트윈 오션<br>
✔ 싱글베드 1개 + 더블베드 1개<br>
✔ 전망: 오션뷰

</div>

<div class="buttons">

<a href="https://www.agoda.com/ko-kr/hotel-sirius_3/hotel/jeju-island-kr.html?countryId=212&finalPriceView=1&isShowMobileAppPrice=false&cid=1439847&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2026-04-9&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=1&showReviewSubmissionEntry=false&currencyCode=KRW&isFreeOccSearch=false&tag=4f122210-314e-4c70-b18b-ac93fc25b69f&tspTypes=8&los=2&searchrequestid=4aca703a-0619-4516-ba02-5543a3db80b6&ds=LzaVtxcYQ9hHA3%2Fs">예약보기</a>

<a class="map" href="https://map.naver.com/p/search/%EA%B7%B8%EB%9D%BC%EB%B2%A8%20%ED%98%B8%ED%85%94/place/35394656?c=15.00,0,0,0,dh&placePath=/home?bk_query=%EA%B7%B8%EB%9D%BC%EB%B2%A8%20%ED%98%B8%ED%85%94&entry=bmp&from=map&fromPanelNum=2&timestamp=202603132357&locale=ko&svcName=map_pcv5&searchText=%EA%B7%B8%EB%9D%BC%EB%B2%A8%20%ED%98%B8%ED%85%94&businessCategory=hotel" target="_blank">지도보기</a>

</div>

</div>
